apiVersion: v2
name: investwise
description: InvestWise Predictor Application Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - fintech
  - ml
  - prediction
  - fastapi
  - nextjs

home: https://github.com/yourusername/InvestWise-Predictor
sources:
  - https://github.com/yourusername/InvestWise-Predictor

maintainers:
  - name: InvestWise Team
    email: team@investwise.com

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 23.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled